# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Import::Account::TDCredit; end
module Rack::QueryParser::InvalidParameterError; end
module Rack::QueryParser::ParameterTypeError; end
module Rack::QueryParser::Params; end
module T::InterfaceWrapper::Helpers; end
module T::Private::Abstract::Hooks; end
module T::Private::Methods::MethodHooks; end
module T::Private::Methods::SingletonMethodHooks; end
